-- CreateTable
CREATE TABLE `Dechet` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('Matin', 'Soir', 'Nuit') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,
    `Quantite` INTEGER NOT NULL DEFAULT 0,
    `Type` VARCHAR(191) NOT NULL,
    `deleted` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
